sudo: required
dist: trusty

env:
 - CABALVER=2.2 GHCVER=8.4.1

addons:
  apt:
    packages:
      - libsdl2-dev

before_install:
 - mkdir -p ~/.local/bin
 - travis_retry sudo add-apt-repository -y ppa:hvr/ghc
 - travis_retry sudo apt-get update
 - travis_retry sudo apt-get install -y cabal-install-$CABALVER ghc-$GHCVER happy-1.19.5 alex-3.1.7
 - travis_retry sudo apt-get install -y libgirepository1.0-dev libwebkitgtk-3.0-dev libwebkit2gtk-3.0-dev libpoppler-glib-dev libvte-2.90-dev libgtksourceview-3.0-dev libgstreamer1.0-dev 
 - export PATH=$HOME/.cabal/bin:/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:/opt/alex/3.1.7/bin:/opt/happy/1.19.5/bin:$HOME/.local/bin:$PATH
 - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

install:
 - cabal --version
 - echo "$(ghc --version) [$(ghc --print-project-git-commit-id 2> /dev/null || echo '?')]"
 - travis_retry cabal update

# Here starts the actual work to be performed for the package under test; any command which exits with a non-zero exit code causes the build to fail.
script:
 - cabal update 
 - cabal install c2hs

 - pushd gi-cairo-render
 - travis_retry cabal install --only-dependencies
 - cabal configure
 - cabal build
 - cabal install
 - cabal haddock
 - popd

 - pushd gi-cairo-connector
 - travis_retry cabal install --only-dependencies
 - cabal configure
 - cabal build
 - cabal install
 - cabal haddock
 - popd 

 - pushd examples/sdl
 - travis_retry cabal install --only-dependencies
 - cabal configure
 - cabal build
 - popd  

 - pushd examples/clock
 - travis_retry cabal install --only-dependencies
 - cabal configure
 - cabal build
 - popd   

cache:
 directories:
 - $HOME/.cabal/packages
 - $HOME/.cabal/store
 - $HOME/.cabal/bin
 - $HOME/.stack

