sudo: true
language: c

cache:
  directories:
  - "$HOME/.cabal/store"

matrix:
  include:
    - os: linux
      dist: xenial
      env: CABALVER=2.2 GHCVER=8.0.2
    - os: linux
      dist: xenial
      env: CABALVER=2.2 GHCVER=8.4.1
    - os: linux
      dist: xenial
      env: CABALVER=2.4 GHCVER=8.6.1
    - os: osx
      osx_image: xcode11

before_install:
 - ./travis/before_install.sh

install:
 - travis_retry ./travis/install.sh

script:
  - ./travis/build.sh

notifications:
  irc:
    channels: "irc.freenode.net#gtk2hs"
    skip_join: true
email: true
