sudo: required
dist: xenial
language: haskell

env:
 - CABALVER=2.2 GHCVER=8.0.2
 - CABALVER=2.2 GHCVER=8.4.1
 - CABALVER=2.4 GHCVER=8.6.1

before_install:
 - travis_retry sudo add-apt-repository -y ppa:webkit-team/ppa
 - travis_retry sudo add-apt-repository -y ppa:hvr/ghc
 - travis_retry sudo apt-get update
 - travis_retry sudo apt-get install -y cabal-install-$CABALVER ghc-$GHCVER happy-1.19.5 alex-3.1.7
 - travis_retry sudo apt-get install -y libgirepository1.0-dev gir1.2-javascriptcoregtk-4.0 libwebkit2gtk-4.0-dev libpoppler-glib-dev libvte-2.91-dev libgtksourceview-3.0-dev libgstreamer-plugins-base1.0-dev libsecret-1-dev
 - export PATH=$HOME/.cabal/bin:/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:/opt/alex/3.1.7/bin:/opt/happy/1.19.5/bin:$PATH
 - export HASKELL_GI_TYPELIB_SEARCH_PATH=/usr/lib/x86_64-linux-gnu/girepository-1.0

install:
 - cabal --version
 - echo "$(ghc --version) [$(ghc --print-project-git-commit-id 2> /dev/null || echo '?')]"
 - travis_retry cabal update

# Here starts the actual work to be performed for the package under test; any command which exits with a non-zero exit code causes the build to fail.
script:
 # The version of Ubuntu in Travis does not have libhandy
 - grep -v Handy cabal.project > cabal.project.new; mv cabal.project.new cabal.project
 # And its gtk version is ancient, so testGtk does not build anymore
 - grep -v haskell-gi-test cabal.project > cabal.project.new; mv cabal.project.new cabal.project
 - pushd bindings
 - cabal new-run genBuildInfo $(./PKGS.sh)
 - popd
 - cabal new-build all
 - cabal new-test
notifications:
  irc:
    channels: "irc.freenode.net#gtk2hs"
    skip_join: true
email: true
