sudo: required
dist: trusty

env:
 - CABALVER=1.24 GHCVER=7.10.3
 - CABALVER=1.24 GHCVER=8.0.1

cache:
  directories:
    - $HOME/.cabal
    - $HOME/.ghc

before_install:
 - travis_retry sudo add-apt-repository -y ppa:hvr/ghc
 - travis_retry sudo apt-get update
 - travis_retry sudo apt-get install -y cabal-install-$CABALVER ghc-$GHCVER happy-1.19.5 alex-3.1.7
 - travis_retry sudo apt-get install -y libgirepository1.0-dev libgtk-3.0-dev
 - export PATH=$HOME/.cabal/bin:/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:/opt/alex/3.1.7/bin:/opt/happy/1.19.5/bin:$PATH

install:
 - cabal --version
 - echo "$(ghc --version) [$(ghc --print-project-git-commit-id 2> /dev/null || echo '?')]"
 - travis_retry cabal update

script:
 - cabal new-build
 - cabal sdist

notifications:
  irc:
    channels: "irc.freenode.net#leksah"
  email: true
